name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
     - # checkout to the repository on the build machine
       name: Checkout
       uses: actions/checkout@v3
     - # login to Docker Hub using the secrets provided
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
     - name: build docker image
       run: docker build -t navneetnishchal/simple-node-app .
     - name: publish docker image
       run: docker push navneetnishchal/simple-node-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from docker Hub
        run: docker pull navneetnishchal/simple-node-app:latest
      - name: run docker image
        run: docker run -d -p 3000:3000 -name node-app navneetnishchal/simple-node-app:latest






       
